### PR TITLE
Get group members live instead of through interval

### PR DESCRIPTION
**Pull request by Powersource**
Because streams are better than setIntervals

### CODE REVIEW

**Comment by Powersource** [comment]
Some test is failing for some reason even though my code is flawless, curious :thinking:

**Comment by staltz** [comment]
I think it's failing now because we have added the invite consent system in tribes2. Gotta update our tests so that added members accept the invite.

**Comment by Powersource** [comment]
The tests in `test/integration/groups.js` all seem to pass except that just at the end when packing up, it throws

```
Uncaught Exception at  uncaughtException : Error: Closed
    at Request._openAndNotClosed (/home/me/prj/ssb/ssb-replication-scheduler/node_modules/.pnpm/random-access-storage@1.4.3/node_modules/random-access-storage/index.js:181:38)
    at Request._run (/home/me/prj/ssb/ssb-replication-scheduler/node_modules/.pnpm/random-access-storage@1.4.3/node_modules/random-access-storage/index.js:208:16)
    at RandomAccessFile.RandomAccess.run (/home/me/prj/ssb/ssb-replication-scheduler/node_modules/.pnpm/random-access-storage@1.4.3/node_modules/random-access-storage/index.js:112:12)
    at RandomAccessFile.RandomAccess.write (/home/me/prj/ssb/ssb-replication-scheduler/node_modules/.pnpm/random-access-storage@1.4.3/node_modules/random-access-storage/index.js:65:8)
    at onWriteLockReleased (/home/me/prj/ssb/ssb-replication-scheduler/node_modules/.pnpm/async-append-only-log@4.3.9/node_modules/async-append-only-log/index.js:174:11)
    at call (/home/me/prj/ssb/ssb-replication-scheduler/node_modules/.pnpm/mutexify@1.4.0/node_modules/mutexify/index.js:8:5)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Review by staltz — APPROVED** [review]
Looks good to merge. Thanks

There are still some weirdness going on in this module and in these tests, but that's somewhat unrelated to these new changes.

**Review by mixmix — APPROVED** [review]
looks great

# :pineapple:

**Pull request merged**
